services:
  - type: web
    name: anime-haven
    runtime: node
    plan: free
    buildCommand: npm install --ignore-scripts && npm rebuild sqlite3 --build-from-source --python=/usr/bin/python3
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: npm_config_build_from_source
        value: "true"
